spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:mysql://localhost:3306/rivo
    username: root
    password: Hari(0127)
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: #database related config
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
#application related config
application:
  security:
    jwt:
      secret-key: 4bb6d1dfbafb64a681139d1586b6f1160d18159afd57c8c79136d7490630407c
      access-token-expiration: 86400000
      refresh-token-expiration: 604800000

cloudinary:
  cloud_name: dgwapjtbp
  api_key: 976424464932446
  api_secret: _Wr7ONrD2FVXTFp8P5WlWPXj6h4

logging:
  level:
    org.springframework.security: DEBUG
